### ISSUE TITLE
Purpose of this Code

### ISSUE THREAD

**Issue by PersnickityPeter** [SiEPIC/SiEPIClab#3]
Hello,
    I am a student who is trying to determine how this code works with the MatLab code from this website:   https://siepic.ubc.ca/probestation . Both this Python code and the Matlab code seem to have different purposes based on the interfaces that are loaded, but since I don't have access to all the same parts like an hp816x laser it is very difficult for me to tell how the code interacts, or even if they're meant to interact at all.

Thank you for any help you might be able to lend me!

**Comment by StephenHLin** [comment]
Hi Peter,

I assisted Michael Caverly in developing the python code. Perhaps I could provide some information that may help.

The Python code is a newer iteration of the Matlab probestation code. It is more stream-lined towards including only the basic functions needed for testing. The Matlab code includes a compilation of many scripts and functions researchers used in the past, hence being very complex. 

I can't speak in detail about the Matlab code as I never delved into them, but for the python code it roughly flows like this:

- **pyOptomip.pyw** (the initial GUI to choose what instruments to connect and loads their respective GUIs)
- **instrumentFrame.py** (secondary GUI that houses each instrument's respective GUI, it can load up to 6 things: 
1. **logWriter.py** (the console window) [Always loaded]
2. **laserPanel.py** (laser's GUI, e.g. hp816x_instr or hp816x_N77Det_instr)
3. **myMatplotlibPanel.py** (a graphing window showing the optical response) [Loaded with a laser instrument]
4. **CorvusEco.py** or **MGMotorPanel.py** (these two are the motors used by the stage, if you have another stage you might have to write your own library)
5. **autoMeasurePanel.py** (this is used to set up automatic measurements given GDS coordinates) [Loaded with a motor instrument]
6. **FineAlignPanel.py** (performs a small stepsize search for the highest power, based on the laser's feedback, in a given region) [Loaded with a motor instrument]

For ease of searching:
- Each **`Panel`**  file houses code related to drawing the GUI box that fits into the instrument frame.
- Each **`Parameter`** houses code for default parameters of the instrument that are added to the drop down list to select in `pyOptomip.pyw`.
- Each **`instr`** file houses the library and functions of that instrument.

I would suggest looking at `MGMotor_instr.py` to start. It has universal motor functions that you should be able to compare back and forth with, e.g.  `getPosition()`, `moveRelative()`.

Hope this helped!
